### PR TITLE
Fix URL formatting, minor typo for image tooltips

### PR DESCRIPTION
**Pull request by dfeeney**
Fixing some minor typo's from viewshare integration.  The tootlip thing is obvious, but the 'a' tag wrapper was stomping on every link in the page when formatting a URL.

I'm assuming you want pull requests to requirejs rather than master.

### CODE REVIEW

**Comment by karger** [comment]
David, unless you are working for zepheira, it would be better to submit 
pull requests to http://simile-widgets.org/exhibit , since that is the 
intended "community version" that is hosted on simile-widgets.org

**Comment by dfeeney** [comment]
Thanks @karger.  I am with Zepheira, but I've submitted a separate pull request to the simile-widgets repo.

**Comment by karger** [comment]
thanks very much!

**Comment by zepheiryan** [comment]
Great, thanks for catching these.

**Pull request merged**
