### PR TITLE
Add ability to load data stored directly in the exhibit html document

### PR DESCRIPTION
**Pull request by karger**
(or any other) by adding a fragment identifier (# suffix) to the link
url.

Data can be embedded by placing it inside a

<script id="#foo" type="application/javascript"></script>

tag and then adding a <link href="#foo" rel="exhibit-data"/> to head.

Fixed a bug in the way persistence.js unpacks relative
URLs.  Previous version resolves "#foo" against base ref
http://example.com/b.html into http://example.com/#foo when it should
be http://example.com/b.html#foo

### CODE REVIEW

**Comment by karger** [comment]
I've replaced the old pull request with this new one which hopefully addresses the issues raised there.

**Comment by zepheiryan** [comment]
Much better, though it doesn't entirely.  You have unconsolidated var declarations, unnecessarily added spaces, you've defined fError and never used it in a method you otherwise don't appear to modify, and you have several undeclared variables (which throws those variables into the global scope, not a good place for them to be).  I suggested you run your code through the jslint task in your previous pull request.  Please do so again.

Making those repairs should make this ready for merging.

**Comment by karger** [comment]
Are you committed to consolidating var declarations?  I find that it 
often makes it harder to read the code so like to keep them 
unconsolidated.

**Comment by karger** [comment]
I get a lot of lint complaints in code that you wrote, which sometimes 
makes me miss some of the complaints about my changes.  Do want me to 
fix your code or leave it alone?

**Comment by karger** [comment]
I've made the requested jslint corrections (that were needed in _my_ changes) and pushed a new commit onto the same branch.

Do I need to give a new pull request?

**Comment by zepheiryan** [comment]
Your latest changes introduces whitespace in files where that's the only change.  Please review your diff (on GitHub, if that helps) and remove spurious changes.  No, you don't need a new pull request, just modify your branch to eliminate the chaff.

Defining variables at the beginning of a scope is common practice in most languages and is intended to reduce programmer error regarding scope.

Lint your own commits.

**Comment by karger** [comment]
I took out the whitespace files.
I jslinted again, but still don't see any complaints I've introduced beyond those already present in the previous file version.

**Comment by zepheiryan** [comment]
Please take out all of the spurious changes.  Again, it would be helpful if you reviewed your diff; what point is there in changing several empty lines - to several empty lines?

You asked about linting everything; my response was to lint just your own commit.

**Comment by zepheiryan** [comment]
Given a commit only encompasses the lines you change, I'm not sure you else you can interpret that.  As a general practice, lint your code.

Remove your unrelated changes to effectively empty lines.  They are the only thing blocking accepting your pull request, which I'm waiting to pull so I can make other changes without forcing to you to generate a new pull request.

**Comment by karger** [comment]
This is done.  Thanks for holding your commit.
I had assumed "my commit" meant "the files I change".  Thanks for clarifying.

**Comment by zepheiryan** [comment]
The new changes you've introduced after removing the whitespace won't pass lint (== instead of ===).  Please get in the habit of using lint before you push.

**Comment by karger** [comment]
fixed.

**Pull request merged**
