### PR TITLE
Add ability to load data stored directly in the exhibit html document

### PR DESCRIPTION
**Pull request by karger**
Add ability to load data stored directly in the exhibit html document
(or any other) by adding a fragment identifier (# suffix) to the link
url.

Data can be embedded by placing it inside a
`<script id="#foo" type="application/javascript"></script>`
tag and then adding a `<link href="#foo" rel="exhibit-data"/>` 
to head.

Fixed a bug in the way persistence.js unpacks relative
URLs.  Previous version resolves "#foo" against base ref
http://example.com/b.html into http://example.com/#foo when it should
be http://example.com/b.html#foo

### CODE REVIEW

**Comment by zepheiryan** [comment]
Please run your code through jslint.  #30 needs to be addressed in full, but it would be nice if new material were run through the general coding standard check before being incorporated (e.g., constrain all `var` declarations to the beginning of the scope in which it belongs).

**Comment by karger** [comment]
I assume you only want me to lint my code changes, and not the whole 
file data.js which generates lots of complaints on code I didn't write. 
   It would be helpful to know which jslint complaints the project 
actually cares about.  Would you be willing to post appropriate jslint 
"settings" that will reveal things that actually must be fixed?  E.g., 
among the options that I _assume_ we would check off are "Assume a 
browser", "tolerate missing 'use strict'", "Tolerate ++ and --", 
"Tolerate many var statements per function" and others.  But it's 
probably a bad idea for me to guess.

**Comment by karger** [comment]
OK, I've run jslint and fixed all the code _I_ wrote in the file.  There 
are numerous other jslint complaints on those files but I didn't want to 
fix them without some sense of the project's jslint rules (see previous 
response).

**Comment by zepheiryan** [comment]
There's an ant task for running the appropriate check.  Read the installation page in the wiki under making changes.

**Comment by zepheiryan** [comment]
To wit, I don't need all of the `function (` instead of `function(` changes scattered throughout importer.js, and I am very much in favor of not tolerating stray var declarations outside of the first few lines of a scope.

**Comment by karger** [comment]
OK, done using lint task in ant.
I'm not certain I'm using "rebase" correctly but the last commit does have the most up to date version of importer.js

**Comment by zepheiryan** [comment]
I must confess I'm not entirely sure what to do with a pull request that functionally comprises just a handful of lines but appears to span fifteen files and thousands of lines of changes.  Perhaps if we close this request and you re-open another that only presents the actual changes in util/persistence.js and data/importer.js it would be a cleaner merge.

**Comment by karger** [comment]
I don't understand.  It is only a handful of lines.  Did I somehow 
accidentally reformat all the whitespace?

**Comment by zepheiryan** [comment]
View this pull request on github.com.  Click on the Diff tab above the initial issue box.

**Comment by karger** [comment]
OK, to keep this clean I've created a brand new revision off the current master and made the few small modifications that actually belong.  We can close this pull request and work on the new one which should solve the problems you raised above.

**Comment by karger** [comment]
Fixed it and submitted a new pull request.

**Pull request closed without merging**
